// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.marcschwieterman.todo;

import com.marcschwieterman.todo.Todo;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect TodoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TodoDataOnDemand: @Component;
    
    private Random TodoDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Todo> TodoDataOnDemand.data;
    
    public Todo TodoDataOnDemand.getNewTransientTodo(int index) {
        com.marcschwieterman.todo.Todo obj = new com.marcschwieterman.todo.Todo();
        obj.setStatus(null);
        obj.setDescription("description_" + index);
        return obj;
    }
    
    public Todo TodoDataOnDemand.getSpecificTodo(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Todo obj = data.get(index);
        return Todo.findTodo(obj.getId());
    }
    
    public Todo TodoDataOnDemand.getRandomTodo() {
        init();
        Todo obj = data.get(rnd.nextInt(data.size()));
        return Todo.findTodo(obj.getId());
    }
    
    public boolean TodoDataOnDemand.modifyTodo(Todo obj) {
        return false;
    }
    
    public void TodoDataOnDemand.init() {
        data = com.marcschwieterman.todo.Todo.findTodoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Todo' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.marcschwieterman.todo.Todo>();
        for (int i = 0; i < 10; i++) {
            com.marcschwieterman.todo.Todo obj = getNewTransientTodo(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
